CREATE TABLE accounts(
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   username TEXT NOT NULL UNIQUE,
   email TEXT NOT NULL
);

CREATE TABLE huddles(
   id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
   date TEXT NOT NULL UNIQUE,
   title TEXT NOT NULL
);

CREATE TABLE participants(
   account_id INTEGER NOT NULL,
   huddle_id INTEGER NOT NULL
);